apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    app: wordpress
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.targetPort }}
  type: LoadBalancer